<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.0.4
 */

/**
 * Database `diseno_sistema`
 */

/* `diseno_sistema`.`municipios` */
$municipios = array(
  array('municipio_id' => '1','nombre' => 'Distrito Nacional','provincia_id' => '5'),
  array('municipio_id' => '2','nombre' => 'Azua de Compostela','provincia_id' => '1'),
  array('municipio_id' => '3','nombre' => 'Estebanía','provincia_id' => '1'),
  array('municipio_id' => '4','nombre' => 'Guayabal','provincia_id' => '1'),
  array('municipio_id' => '5','nombre' => 'Las Charcas','provincia_id' => '1'),
  array('municipio_id' => '6','nombre' => 'Las Yayas de Viajama','provincia_id' => '1'),
  array('municipio_id' => '7','nombre' => 'Padre Las Casas','provincia_id' => '1'),
  array('municipio_id' => '8','nombre' => 'Peralta','provincia_id' => '1'),
  array('municipio_id' => '9','nombre' => 'Pueblo Viejo','provincia_id' => '1'),
  array('municipio_id' => '10','nombre' => 'Sabana Yegua','provincia_id' => '1'),
  array('municipio_id' => '11','nombre' => 'Tábara Arriba','provincia_id' => '1'),
  array('municipio_id' => '12','nombre' => 'Neiba','provincia_id' => '2'),
  array('municipio_id' => '13','nombre' => 'Galván','provincia_id' => '2'),
  array('municipio_id' => '14','nombre' => 'Los Ríos','provincia_id' => '2'),
  array('municipio_id' => '15','nombre' => 'Tamayo','provincia_id' => '2'),
  array('municipio_id' => '16','nombre' => 'Villa Jaragua','provincia_id' => '2'),
  array('municipio_id' => '17','nombre' => 'Barahona','provincia_id' => '3'),
  array('municipio_id' => '18','nombre' => 'Cabral','provincia_id' => '3'),
  array('municipio_id' => '19','nombre' => 'El Peñón','provincia_id' => '3'),
  array('municipio_id' => '20','nombre' => 'Enriquillo','provincia_id' => '3'),
  array('municipio_id' => '21','nombre' => 'Fundación','provincia_id' => '3'),
  array('municipio_id' => '22','nombre' => 'Jaquimeyes','provincia_id' => '3'),
  array('municipio_id' => '23','nombre' => 'La Ciénaga','provincia_id' => '3'),
  array('municipio_id' => '24','nombre' => 'Las Salinas','provincia_id' => '3'),
  array('municipio_id' => '25','nombre' => 'Paraíso','provincia_id' => '3'),
  array('municipio_id' => '26','nombre' => 'Polo','provincia_id' => '3'),
  array('municipio_id' => '27','nombre' => 'Vicente Noble','provincia_id' => '3'),
  array('municipio_id' => '28','nombre' => 'Dajabón','provincia_id' => '4'),
  array('municipio_id' => '29','nombre' => 'El Pino','provincia_id' => '4'),
  array('municipio_id' => '30','nombre' => 'Loma de Cabrera','provincia_id' => '4'),
  array('municipio_id' => '31','nombre' => 'Partido','provincia_id' => '4'),
  array('municipio_id' => '32','nombre' => 'Restauración','provincia_id' => '4'),
  array('municipio_id' => '33','nombre' => 'San Francisco de Macorís','provincia_id' => '6'),
  array('municipio_id' => '34','nombre' => 'Arenoso','provincia_id' => '6'),
  array('municipio_id' => '35','nombre' => 'Castillo','provincia_id' => '6'),
  array('municipio_id' => '36','nombre' => 'Eugenio María de Hostos','provincia_id' => '6'),
  array('municipio_id' => '37','nombre' => 'Las Guáranas','provincia_id' => '6'),
  array('municipio_id' => '38','nombre' => 'Pimentel','provincia_id' => '6'),
  array('municipio_id' => '39','nombre' => 'Villa Riva','provincia_id' => '6'),
  array('municipio_id' => '40','nombre' => 'El Seibo','provincia_id' => '8'),
  array('municipio_id' => '41','nombre' => 'Miches','provincia_id' => '8'),
  array('municipio_id' => '42','nombre' => 'Comendador','provincia_id' => '7'),
  array('municipio_id' => '43','nombre' => 'Bánica','provincia_id' => '7'),
  array('municipio_id' => '44','nombre' => 'El Llano','provincia_id' => '7'),
  array('municipio_id' => '45','nombre' => 'Hondo Valle','provincia_id' => '7'),
  array('municipio_id' => '46','nombre' => 'Juan Santiago','provincia_id' => '7'),
  array('municipio_id' => '47','nombre' => 'Pedro Santana','provincia_id' => '7'),
  array('municipio_id' => '48','nombre' => 'Moca','provincia_id' => '9'),
  array('municipio_id' => '49','nombre' => 'Cayetano Germosén','provincia_id' => '9'),
  array('municipio_id' => '50','nombre' => 'Gaspar Hernández','provincia_id' => '9'),
  array('municipio_id' => '51','nombre' => 'Jamao al Norte','provincia_id' => '9'),
  array('municipio_id' => '52','nombre' => 'Hato Mayor del Rey','provincia_id' => '10'),
  array('municipio_id' => '53','nombre' => 'El Valle','provincia_id' => '10'),
  array('municipio_id' => '54','nombre' => 'Sabana de la Mar','provincia_id' => '10'),
  array('municipio_id' => '55','nombre' => 'Salcedo','provincia_id' => '11'),
  array('municipio_id' => '56','nombre' => 'Tenares','provincia_id' => '11'),
  array('municipio_id' => '57','nombre' => 'Villa Tapia','provincia_id' => '11'),
  array('municipio_id' => '58','nombre' => 'Jimaní','provincia_id' => '12'),
  array('municipio_id' => '59','nombre' => 'Cristóbal','provincia_id' => '12'),
  array('municipio_id' => '60','nombre' => 'Duvergé','provincia_id' => '12'),
  array('municipio_id' => '61','nombre' => 'La Descubierta','provincia_id' => '12'),
  array('municipio_id' => '62','nombre' => 'Mella','provincia_id' => '12'),
  array('municipio_id' => '63','nombre' => 'Postrer Río','provincia_id' => '12'),
  array('municipio_id' => '64','nombre' => 'Higüey','provincia_id' => '13'),
  array('municipio_id' => '65','nombre' => 'San Rafael del Yuma','provincia_id' => '13'),
  array('municipio_id' => '66','nombre' => 'La Romana','provincia_id' => '14'),
  array('municipio_id' => '67','nombre' => 'Guaymate','provincia_id' => '14'),
  array('municipio_id' => '68','nombre' => 'Villa Hermosa','provincia_id' => '14'),
  array('municipio_id' => '69','nombre' => 'La Concepción de La Vega','provincia_id' => '15'),
  array('municipio_id' => '70','nombre' => 'Constanza','provincia_id' => '15'),
  array('municipio_id' => '71','nombre' => 'Jarabacoa','provincia_id' => '15'),
  array('municipio_id' => '72','nombre' => 'Jima Abajo','provincia_id' => '15'),
  array('municipio_id' => '73','nombre' => 'Nagua','provincia_id' => '16'),
  array('municipio_id' => '74','nombre' => 'Cabrera','provincia_id' => '16'),
  array('municipio_id' => '75','nombre' => 'El Factor','provincia_id' => '16'),
  array('municipio_id' => '76','nombre' => 'Río San Juan','provincia_id' => '16'),
  array('municipio_id' => '77','nombre' => 'Bonao','provincia_id' => '17'),
  array('municipio_id' => '78','nombre' => 'Maimón','provincia_id' => '17'),
  array('municipio_id' => '79','nombre' => 'Piedra Blanca','provincia_id' => '17'),
  array('municipio_id' => '80','nombre' => 'Montecristi','provincia_id' => '18'),
  array('municipio_id' => '81','nombre' => 'Castañuela','provincia_id' => '18'),
  array('municipio_id' => '82','nombre' => 'Guayubín','provincia_id' => '18'),
  array('municipio_id' => '83','nombre' => 'Las Matas de Santa Cruz','provincia_id' => '18'),
  array('municipio_id' => '84','nombre' => 'Pepillo Salcedo','provincia_id' => '18'),
  array('municipio_id' => '85','nombre' => 'Villa Vásquez','provincia_id' => '18'),
  array('municipio_id' => '86','nombre' => 'Monte Plata','provincia_id' => '19'),
  array('municipio_id' => '87','nombre' => 'Bayaguana','provincia_id' => '19'),
  array('municipio_id' => '88','nombre' => 'Peralvillo','provincia_id' => '19'),
  array('municipio_id' => '89','nombre' => 'Sabana Grande de Boyá','provincia_id' => '19'),
  array('municipio_id' => '90','nombre' => 'Yamasá','provincia_id' => '19'),
  array('municipio_id' => '91','nombre' => 'Pedernales','provincia_id' => '20'),
  array('municipio_id' => '92','nombre' => 'Oviedo','provincia_id' => '20'),
  array('municipio_id' => '93','nombre' => 'Baní','provincia_id' => '21'),
  array('municipio_id' => '94','nombre' => 'Nizao','provincia_id' => '21'),
  array('municipio_id' => '95','nombre' => 'Puerto Plata','provincia_id' => '22'),
  array('municipio_id' => '96','nombre' => 'Altamira','provincia_id' => '22'),
  array('municipio_id' => '97','nombre' => 'Guananico','provincia_id' => '22'),
  array('municipio_id' => '98','nombre' => 'Imbert','provincia_id' => '22'),
  array('municipio_id' => '99','nombre' => 'Los Hidalgos','provincia_id' => '22'),
  array('municipio_id' => '100','nombre' => 'Luperón','provincia_id' => '22'),
  array('municipio_id' => '101','nombre' => 'Sosúa','provincia_id' => '22'),
  array('municipio_id' => '102','nombre' => 'Villa Isabela','provincia_id' => '22'),
  array('municipio_id' => '103','nombre' => 'Villa Montellano','provincia_id' => '22'),
  array('municipio_id' => '104','nombre' => 'Samaná','provincia_id' => '23'),
  array('municipio_id' => '105','nombre' => 'Las Terrenas','provincia_id' => '23'),
  array('municipio_id' => '106','nombre' => 'Sánchez','provincia_id' => '23'),
  array('municipio_id' => '107','nombre' => 'San Cristóbal','provincia_id' => '25'),
  array('municipio_id' => '108','nombre' => 'Bajos de Haina','provincia_id' => '25'),
  array('municipio_id' => '109','nombre' => 'Cambita Garabito','provincia_id' => '25'),
  array('municipio_id' => '110','nombre' => 'Los Cacaos','provincia_id' => '25'),
  array('municipio_id' => '111','nombre' => 'Sabana Grande de Palenque','provincia_id' => '25'),
  array('municipio_id' => '112','nombre' => 'San Gregorio de Nigua','provincia_id' => '25'),
  array('municipio_id' => '113','nombre' => 'Villa Altagracia','provincia_id' => '25'),
  array('municipio_id' => '114','nombre' => 'Yaguate','provincia_id' => '25'),
  array('municipio_id' => '115','nombre' => 'San José de Ocoa','provincia_id' => '26'),
  array('municipio_id' => '116','nombre' => 'Rancho Arriba','provincia_id' => '26'),
  array('municipio_id' => '117','nombre' => 'Sabana Larga','provincia_id' => '26'),
  array('municipio_id' => '118','nombre' => 'San Juan de la Maguana','provincia_id' => '27'),
  array('municipio_id' => '119','nombre' => 'Bohechío','provincia_id' => '27'),
  array('municipio_id' => '120','nombre' => 'El Cercado','provincia_id' => '27'),
  array('municipio_id' => '121','nombre' => 'Juan de Herrera','provincia_id' => '27'),
  array('municipio_id' => '122','nombre' => 'Las Matas de Farfán','provincia_id' => '27'),
  array('municipio_id' => '123','nombre' => 'Vallejuelo','provincia_id' => '27'),
  array('municipio_id' => '124','nombre' => 'San Pedro de Macorís','provincia_id' => '28'),
  array('municipio_id' => '125','nombre' => 'Consuelo','provincia_id' => '28'),
  array('municipio_id' => '126','nombre' => 'Guayacanes','provincia_id' => '28'),
  array('municipio_id' => '127','nombre' => 'Quisqueya','provincia_id' => '28'),
  array('municipio_id' => '128','nombre' => 'Ramón Santana','provincia_id' => '28'),
  array('municipio_id' => '129','nombre' => 'San José de Los Llanos','provincia_id' => '28'),
  array('municipio_id' => '130','nombre' => 'Cotuí','provincia_id' => '24'),
  array('municipio_id' => '131','nombre' => 'Cevicos','provincia_id' => '24'),
  array('municipio_id' => '132','nombre' => 'Fantino','provincia_id' => '24'),
  array('municipio_id' => '133','nombre' => 'La Mata','provincia_id' => '24'),
  array('municipio_id' => '134','nombre' => 'Santiago','provincia_id' => '29'),
  array('municipio_id' => '135','nombre' => 'Bisonó','provincia_id' => '29'),
  array('municipio_id' => '136','nombre' => 'Jánico','provincia_id' => '29'),
  array('municipio_id' => '137','nombre' => 'Licey al Medio','provincia_id' => '29'),
  array('municipio_id' => '138','nombre' => 'Puñal','provincia_id' => '29'),
  array('municipio_id' => '139','nombre' => 'Sabana Iglesia','provincia_id' => '29'),
  array('municipio_id' => '140','nombre' => 'San José de las Matas','provincia_id' => '29'),
  array('municipio_id' => '141','nombre' => 'Tamboril','provincia_id' => '29'),
  array('municipio_id' => '142','nombre' => 'Villa González','provincia_id' => '29'),
  array('municipio_id' => '143','nombre' => 'San Ignacio de Sabaneta','provincia_id' => '30'),
  array('municipio_id' => '144','nombre' => 'Los Almácigos','provincia_id' => '30'),
  array('municipio_id' => '145','nombre' => 'Monción','provincia_id' => '30'),
  array('municipio_id' => '146','nombre' => 'Santo Domingo Este','provincia_id' => '31'),
  array('municipio_id' => '147','nombre' => 'Boca Chica','provincia_id' => '31'),
  array('municipio_id' => '148','nombre' => 'Los Alcarrizos','provincia_id' => '31'),
  array('municipio_id' => '149','nombre' => 'Pedro Brand','provincia_id' => '31'),
  array('municipio_id' => '150','nombre' => 'San Antonio de Guerra','provincia_id' => '31'),
  array('municipio_id' => '151','nombre' => 'Santo Domingo Norte','provincia_id' => '31'),
  array('municipio_id' => '152','nombre' => 'Santo Domingo Oeste','provincia_id' => '31'),
  array('municipio_id' => '153','nombre' => 'Mao','provincia_id' => '32'),
  array('municipio_id' => '154','nombre' => 'Esperanza','provincia_id' => '32'),
  array('municipio_id' => '155','nombre' => 'Laguna Salada','provincia_id' => '32')
);
